/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class

        //TODO: call your test case functions one after other here
        imageUrl image =new imageUrl();
      // LinkedIn Linkedin =new LinkedIn();
       //GoogleSearchTest googleSearchTest=new GoogleSearchTest();
       //WindowHandleExample windowHandleExample=new WindowHandleExample();
       //NestedFramesText nestedFramesText=new NestedFramesText();
       //CountHyperlinks countHyperlinks=new CountHyperlinks();
      // IMDbRatings imDbRatings=new IMDbRatings();

       // tests.testCase01();
        image.testCase01();
        
       //Linkedin.TestCase01();
        //googleSearchTest.TestCase01();
       //windowHandleExample.TestCase01();
       //nestedFramesText.testCase01();
       //countHyperlinks.testCase01();
       //imDbRatings.testCase01();
        

        //END Tests


        //tests.endTest(); // End your test by clearning connections and closing browser
        //Linkedin.endTest();
       // googleSearchTest.endTest();
       //windowHandleExample.endTest();
       //nestedFramesText.endTest();
       //countHyperlinks.endTest();
       //imDbRatings.endTest();
       image.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
